### ISSUE TITLE
Annotating prediction causes fatal crash

### ISSUE THREAD

**Issue by mikailweston** [jcornford/pyecog#70]
1. load prediction csv file
2. click on prediction
3. attempt to create a new annotation in a different part of that H5 file
4. crash:

Traceback (most recent call last):
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 407, in master_tree_selection
    self.tree_selection_file_dir()
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 468, in tree_selection_file_dir
    self.handle_tid_for_file_dir_plotting() # this will automatically call the plotting by changing the v
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 514, in handle_tid_for_file_dir_plotting
    self.load_filedir_h5_file(current_spinbox_id)
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 481, in load_filedir_h5_file
    h5 = H5File(fpath)
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\ndf\h5loader.py", line 77, in __init__
    with h5py.File(self.filepath, 'r+') as f:
  File "C:\Users\mweston\Anaconda3\envs\pyecogdev\lib\site-packages\h5py\_hl\files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Users\mweston\Anaconda3\envs\pyecogdev\lib\site-packages\h5py\_hl\files.py", line 94, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2705)
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\_objects.c:2663)
  File "h5py\h5f.pyx", line 76, in h5py.h5f.open (C:\Minonda\conda-bld\h5py_1474482825505\work\h5py\h5f.c:1951)
OSError: Unable to open file (Unable to open file: name = 'f:/rig4_4_h5\m1515668039_2018-01-11-10-53-59_tids_[73].h5', errno = 2, error message = 'no such file or directory', flags = 1, o_flags = 2)

**Comment by mikailweston** [comment]
bug fix now gives:

`Traceback (most recent call last):
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 401, in master_tree_selection
    self.tree_selection_file_dir()
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 445, in tree_selection_file_dir
    self.handle_tid_for_file_dir_plotting() # this will automatically call the plotting by changing the v
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 471, in handle_tid_for_file_dir_plotting
    self.load_filedir_h5_file(current_spinbox_id)
  File "C:\Users\mweston\Documents\GitHub\pyecog\pyecog\visualisation\pyecog_main_gui.py", line 483, in load_filedir_h5_file
    path = self.startname_to_full(fpath_filetree[:11])
TypeError: 'dict' object is not callable`
